"""Typed schemas used at application boundaries."""

from app.schemas.autopost import (
    AutopostAccount,
    AutopostErrorCode,
    AutopostRun,
    AutopostRunStatus,
    AutopostSettings,
    AutopostStatus,
)
from app.schemas.content_engine import (
    ContentAngle,
    ContentBrief,
    ContentDraftHook,
    ContentFormat,
    ContentGenerationDraft,
    ContentGenerationResponse,
    ContentHook,
    ContentMetadata,
    ContentQuality,
)
from app.schemas.llm import (
    Hook,
    HookType,
    NeuroCommentResponse,
    PostGenerationResponse,
    RadarAnalysisResponse,
    ThreadGenerationResponse,
    VoiceProfileResponse,
)
from app.schemas.feedback import (
    AccountFeedbackResult,
    BrainPatternWrite,
    GoalSelection,
    MetricScore,
    PatternAggregate,
    PostBaseline,
    PostFeature,
    PostPerformance,
)
from app.schemas.social_brain import (
    BrainEvent,
    BrainPattern,
    BrainRecord,
    BrainTaskContext,
)

__all__ = [
    "AutopostAccount",
    "AutopostErrorCode",
    "AutopostRun",
    "AutopostRunStatus",
    "AutopostSettings",
    "AutopostStatus",
    "ContentAngle",
    "ContentBrief",
    "ContentDraftHook",
    "ContentFormat",
    "ContentGenerationDraft",
    "ContentGenerationResponse",
    "ContentHook",
    "ContentMetadata",
    "ContentQuality",
    "Hook",
    "HookType",
    "NeuroCommentResponse",
    "PostGenerationResponse",
    "RadarAnalysisResponse",
    "ThreadGenerationResponse",
    "VoiceProfileResponse",
    "AccountFeedbackResult",
    "BrainPatternWrite",
    "GoalSelection",
    "MetricScore",
    "PatternAggregate",
    "PostBaseline",
    "PostFeature",
    "PostPerformance",
    "BrainEvent",
    "BrainPattern",
    "BrainRecord",
    "BrainTaskContext",
]
